name: Generate Blog Feed

on:
  schedule:
    - cron: "0 * * * *"  # 매 시간 실행
  workflow_dispatch:      # 수동 실행 허용

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate HTML
        run: node generate.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
